//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veiculo
    {
        public int ID { get; set; }
        public string Placa { get; set; }
        public string Renavam { get; set; }
        public string NomeProprietario { get; set; }
        public string CPFProprietario { get; set; }
        public bool Bloqueado { get; set; }
    }
}
